language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

script: python pasteee.py -v

notifications:
    email:
        on_success: never
        on_failure: never

sudo: false
